on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["7.4", "7.5", "current"]
        racket-variant: ["regular", "CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.3
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: sudo raco pkg install --batch --auto web-server-lib/ web-server-doc/ web-server-test/ web-server/
      - run: raco test --drdr web-server-test/
